///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : sensorfusion.cpp
/// SOFTWARE COMPONENT NAME           : SensorFusion
/// GENERATED DATE                    : 2024-11-04 08:32:44
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "sensorfusion/aa/sensorfusion.h"
 
#include <cstdint>
#include <vector>
#include <opencv2/opencv.hpp>

namespace sensorfusion
{
namespace aa
{
 
SensorFusion::SensorFusion()
    : m_logger(ara::log::CreateLogger("SENF", "SWC", ara::log::LogLevel::kVerbose))
    , m_workers(4)
{
}
 
SensorFusion::~SensorFusion()
{
}
 
bool SensorFusion::Initialize()
{
    m_logger.LogVerbose() << "SensorFusion::Initialize";
    
    bool init{true};
    
    m_CameraData = std::make_shared<sensorfusion::aa::port::CameraData>();
    m_FusionData = std::make_shared<sensorfusion::aa::port::FusionData>();
    m_LidarData = std::make_shared<sensorfusion::aa::port::LidarData>();
    m_SimulationData = std::make_shared<sensorfusion::aa::port::SimulationData>();
    
    return init;
}
 
void SensorFusion::Start()
{
    m_logger.LogVerbose() << "SensorFusion::Start";
    
    m_CameraData->Start();
    m_FusionData->Start();
    m_LidarData->Start();
    m_SimulationData->Start();
    
    // run software component
    Run();
}
 
void SensorFusion::Terminate()
{
    m_logger.LogVerbose() << "SensorFusion::Terminate";
    
    m_CameraData->Terminate();
    m_FusionData->Terminate();
    m_LidarData->Terminate();
    m_SimulationData->Terminate();
}
 
void SensorFusion::Run()
{
    m_logger.LogVerbose() << "SensorFusion::Run";
    
    m_workers.Async([this] { TaskReceiveCEventCyclic(); });
    m_workers.Async([this] { m_FusionData->SendEventFEventCyclic(); });
    m_workers.Async([this] { m_LidarData->ReceiveEventLEventCyclic(); });
    m_workers.Async([this] { m_SimulationData->ReceiveEventSEventCyclic(); });
    
    m_workers.Wait();
}

void SensorFusion::TaskReceiveCEventCyclic()
{
    m_CameraData->SetReceiveEventCEventHandler([this](const auto& sample)
    {
        OnReceiveCEvent(sample);
    });
    m_CameraData->ReceiveEventCEventCyclic();
}

void SensorFusion::OnReceiveCEvent(const deepracer::service::cameradata::proxy::events::CEvent::SampleType& sample)
{
    std::vector<float> vec = {18.18f, 28.28f};

    // ControlData 서비스의 CEvent로 전송해야 할 값을 변경한다. 이 함수는 전송 타겟 값을 변경할 뿐 실제 전송은 다른 부분에서 진행된다.
    m_FusionData->WriteDataFEvent(vec);
    m_logger.LogInfo() << "SensorFusion::OnReceiveCEvent(" << sample[1] << ")";
}
 
} /// namespace aa
} /// namespace sensorfusion
