///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : sensor.cpp
/// SOFTWARE COMPONENT NAME           : Sensor
/// GENERATED DATE                    : 2024-11-04 08:32:44
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "sensor/aa/sensor.h"

#include <cstdint>
#include <vector>
#include <opencv2/opencv.hpp>
 
namespace sensor
{
namespace aa
{
 
Sensor::Sensor()
    : m_logger(ara::log::CreateLogger("SENS", "SWC", ara::log::LogLevel::kVerbose))
    , m_workers(3)
    , m_running(false)
{
}
 
Sensor::~Sensor()
{
}
 
bool Sensor::Initialize()
{
    m_logger.LogVerbose() << "Sensor::Initialize";
    
    bool init{true};
    
    m_CameraData = std::make_shared<sensor::aa::port::CameraData>();
    m_LidarData = std::make_shared<sensor::aa::port::LidarData>();
    
    return init;
}
 
void Sensor::Start()
{
    m_logger.LogVerbose() << "Sensor::Start";
    
    m_CameraData->Start();
    m_LidarData->Start();
    
    // run software component
    Run();
}
 
void Sensor::Terminate()
{
    m_logger.LogVerbose() << "Sensor::Terminate";
    
    m_running = false;

    m_CameraData->Terminate();
    m_LidarData->Terminate();
}
 
void Sensor::Run()
{
    m_logger.LogVerbose() << "Sensor::Run";

    m_running = true;
    
    m_workers.Async([this] { TaskGenerateCEventValue(); });
    m_workers.Async([this] { m_CameraData->SendEventCEventCyclic(); });
    m_workers.Async([this] { m_LidarData->SendEventLEventCyclic(); });
    
    m_workers.Wait();
}

void Sensor::TaskGenerateCEventValue()
{
    // Camera 객체 생성
    cv::VideoCapture cap1(0);
    cv::VideoCapture cap2(2);

    // 접근 여부 파악
    if (!cap1.isOpened()) {
        m_logger.LogVerbose() << "Cant Open Camera1";
    }else{
        m_logger.LogInfo() << "Open Camera1 Successfully";
    }

    if (!cap2.isOpened()) {
        m_logger.LogVerbose() << "Cant Open Camera2";
    }else{
        m_logger.LogInfo() << "Open Camera2 Successfully";
    }

    // MJPEC 코덱 및 크기 설정
    cap1.set(cv::CAP_PROP_FOURCC, cv::VideoWriter::fourcc('M', 'J', 'P', 'G'));
    cap1.set(cv::CAP_PROP_FRAME_WIDTH, 160);
    cap1.set(cv::CAP_PROP_FRAME_HEIGHT, 120);

    cap2.set(cv::CAP_PROP_FOURCC, cv::VideoWriter::fourcc('M', 'J', 'P', 'G'));
    cap2.set(cv::CAP_PROP_FRAME_WIDTH, 160);
    cap2.set(cv::CAP_PROP_FRAME_HEIGHT, 120);

    m_logger.LogInfo() << "Setting CODEC Successfully";
    
    cv::Mat frame1;
    cv::Mat frame2;
    cv::Mat frame1_grayscaled;
    cv::Mat frame2_grayscaled;
    std::vector<uint8_t> buffer1;
    std::vector<uint8_t> buffer2;

    cap1 >> frame1;
    cap2 >> frame2;
    // cv::imshow("frame1", frame1);
    // cv::imshow("frame2", frame2);
	// cv::waitKey(0);

    int rows1 = frame1.rows;
    int cols1 = frame1.cols;
    int arraySize1 = rows1*cols1;
    m_logger.LogInfo() << "Frame1 rows size :  = " << rows1;
    m_logger.LogInfo() << "Frame1 cols size :  = " << cols1;
    m_logger.LogInfo() << "Frame1 array size :  = " << arraySize1;

    int rows2 = frame2.rows;
    int cols2 = frame2.cols;
    int arraySize2 = rows2*cols2;
    m_logger.LogInfo() << "Frame2 rows size :  = " << rows2;
    m_logger.LogInfo() << "Frame2 cols size :  = " << cols2;
    m_logger.LogInfo() << "Frame2 array size :  = " << arraySize2;

    if (!frame1.empty()){
        //GrayScale
        cv::cvtColor(frame1, frame1_grayscaled, cv::COLOR_BGR2GRAY);
        
        m_logger.LogInfo() << "Camera frames processed";
        m_logger.LogInfo() << "GrayScaled frame1 rows size :  = " << frame1_grayscaled.rows;
        m_logger.LogInfo() << "GrayScaled frame1 cols size :  = " << frame1_grayscaled.cols;
    }

    if (!frame2.empty()){
        //GrayScale
        cv::cvtColor(frame2, frame2_grayscaled, cv::COLOR_BGR2GRAY);
        
        m_logger.LogInfo() << "Camera frames processed";
        m_logger.LogInfo() << "GrayScaled frame2 rows size :  = " << frame2_grayscaled.rows;
        m_logger.LogInfo() << "GrayScaled frame2 cols size :  = " << frame2_grayscaled.cols;
    }

    while (m_running)
    {
        //카메라 캡처
        cap1 >> frame1;
        cap2 >> frame2;

        m_logger.LogInfo() << "Frame1 rows size :  = " << frame1.rows;
        m_logger.LogInfo() << "Frame1 cols size :  = " << frame1.cols;
        m_logger.LogInfo() << "Frame1 array size :  = " << frame1.rows * frame1.cols;

        //GrayScale
        cv::cvtColor(frame1, frame1_grayscaled, cv::COLOR_BGR2GRAY);
        cv::cvtColor(frame2, frame2_grayscaled, cv::COLOR_BGR2GRAY);

        m_logger.LogInfo() << "GrayScale Processing Succesfully";

        //Flatten
        cv::imencode(".jpeg", frame1, buffer1);
        cv::imencode(".jpeg", frame2, buffer2);

        m_logger.LogInfo() << "Bitmap Flatten";

        cv::imshow("frame1_grayscaled", frame1_grayscaled);
        cv::imshow("frame2_grayscaled", frame2_grayscaled);
        if (cv::waitKey(10) == 27){	// 10ms 동안 키보드 입력s 대기, 키보드 입력고 있고 해당 키값이 ESC 면 루프 나감
			m_running = false;
	    }

        deepracer::service::cameradata::skeleton::events::CEvent::SampleType settingSampleValue = buffer1;
        // CameraData 서비스의 CEvent로 전송해야 할 값을 변경한다. 이 함수는 전송 타겟 값을 변경할 뿐 실제 전송은 다른 부분에서 진행된다.
        m_CameraData->WriteDataCEvent(settingSampleValue);

        m_logger.LogInfo() << "Sensor::Call CameraData->WriteDataCEvent(" << settingSampleValue[1] << ")";

        std::this_thread::sleep_for(std::chrono::seconds(0.1));
    }

    cap1.release();
    cap2.release();
}
 
 
} /// namespace aa
} /// namespace sensor
